# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-30 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='SOME STRING', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Username',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='data_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 30, 4, 0, 54, 924969, tzinfo=utc)),
        ),
    ]
