# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-30 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160330_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='article',
            name='data_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 30, 4, 4, 18, 869174, tzinfo=utc)),
        ),
    ]
