# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-20 18:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20160420_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 20, 18, 59, 15, 325746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
